# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Umesh's Musings"

# A description of your site for meta tag, search engine results.
description: "Work. Learn. Scratches."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl:

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://umesh-timalsina.github.io"

# Favicon
favicon: images/favicon.png

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Archives
    url: /tags

# The shortname for your Disqus site to enable comments.
disqus: umesh-blog

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Umesh Timalsina. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'
# Plugins
plugins: [ jekyll-paginate, jemoji ]


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge


# Sass
sass:
  sass_dir: _sass
  style: compressed
